name: Acceptance tests
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0-beta1
      - uses: actions/checkout@v2
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - uses: engineerd/setup-kind@v0.5.0
      - name: test (server side plan enabled)
        run: |
          make testacc KUBE_CONFIG_PATH="${HOME}/.kube/config"
      - name: test (server side plan disabled)
        env:
          TESTARGS: "-server-side-plan=false"
        run: |
          make testacc KUBE_CONFIG_PATH="${HOME}/.kube/config"
