name: "check examples"
on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@master
    - uses: engineerd/setup-kind@v0.3.0
    - name: Check examples
      run: ./scripts/check_examples.sh
      shell: bash 
