name: Check examples
on:
  push:
    branches:
      - master
      - main
    paths:
      - "examples/**"
      - "**.go"
  pull_request:
    branches:
      - master
    paths:
      - "examples/**"
      - "**.go"
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version:
          - "0.14.10"
          - "0.15.0"
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - uses: actions/checkout@v2
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"
      - name: Check examples run
        run: make check-examples
        env:
          TERM: xterm-256color
